version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist --cwd ./laravel-ci
      - run: npm ci --cwd ./laravel-ci
      - run: npm run dev --cwd ./laravel-ci
      - run:
          name: php test
          command: vendor/bin/phpunit --cwd ./laravel-ci