version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
          environment:
            - APP_ENV: testing
            - DB_CONNECTION: mysql
            - DB_HOST: localhost
            - DB_PORT: 5432
            - DB_DATABASE: larasns
            - DB_USERNAME: root
      - image: circleci/mysql:8.0
          environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD: true
            - MYSQL_DATABASE: larasns
    steps:
      - checkout
      - run:
          working_directory: laravel-ci
          command: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "laravel-ci/composer.lock" }}
      - run:
          working_directory: laravel-ci
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "laravel-ci/composer.lock" }}
          paths:
            - laravel-ci/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "laravel-ci/package-lock.json" }}
      - run:
          name: npm ci
          working_directory: laravel-ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi 
      - save_cache:
          key: npm-v1-{{ checksum "laravel-ci/package-lock.json" }}
          paths:
            - laravel-ci/node_modules
      - run:
          working_directory: laravel-ci
          command: npm run dev
      - run:
          name: get ready for mysql
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo pdo_mysql
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          working_directory: laravel-ci
          name: php test
          command: vendor/bin/phpunit